version: "3.9"

services:
  react-app:
    container_name: react-app
    build: ./docker/react
    volumes:
      - .:/app:cached
    ports:
      - "5173:5173"
      - "24678:24678"
    tty: true
    environment:
      - VITE_USE_EMULATOR=true
    command: sh -c "npm install && npm run dev"
  firebase-emulator:
    container_name: firebase-emulator
    build: ./docker/firebase
    volumes:
      - ./.firebaserc:/opt/firebase/.firebaserc
      - ./firebase.json:/opt/firebase/firebase.json
      - ./firestore.rules:/opt/firebase/firestore.rules
      - ./storage.rules:/opt/firebase/storage.rules
      - ./docker/firebase/bin/:/root/.cache:cached
      - ./docker/firebase/config/:/root/.config:cached
      - ./docker/firebase/src:/opt/firebase/
      - ./seed:/opt/firebase/seed
      - ./functions:/opt/firebase/functions
    ports:
      - 9199:9199
      - 9099:9099
      - 8080:8080
      - 5050:5050
      - 5001:5001
      - 4000:4000
    tty: true
    working_dir: /opt/firebase
    command: firebase emulators:start --import=./seed

volumes:
  node_modules:
