export const ERAS = [
  { value: "under 10", name: "10代以下" },
  { value: "early teens", name: "10代前半" },
  { value: "late teens", name: "10代後半" },
  { value: "early 20's", name: "20代前半" },
  { value: "late 20's", name: "20代後半" },
  { value: "early 30's", name: "30代前半" },
  { value: "late 30's", name: "30代後半" },
  { value: "early 40's", name: "40代前半" },
  { value: "late 40's", name: "40代後半" },
  { value: "early 50's", name: "50代前半" },
  { value: "late 50's", name: "50代後半" },
  { value: "early 60's", name: "60代前半" },
  { value: "late 60's", name: "60代後半" },
  { value: "over 70's", name: "70代以上" },
];
