name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker/react
          push: true
          tags: ucho456/lite-chat-react-app:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: docker.io
          DOCKER_BUILDKIT: 1
          DOCKER_BUILDKIT_SESSION_ID: random
          DOCKER_ALLOW_NONE_AUTHENTICATION: 1
      - name: Build and test Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker/react
          dockerfile: Dockerfile
          push: false
        env:
          CI: true
      - name: Test with Docker image
        with:
          context: .
        run: |
          docker run ucho456/lite-chat-react-app:latest npm run test
